### PR TITLE
add command to install virtualenv package

### LINKED ISSUE #133: add command to install virtualenv package before cppyy installation
the docs for installation of cppyy don't contain enough steps to install virtualenv.

image

So I recommend adding a command to install virtualenv package to be able to create a virtual environment in order to install cppyy inside it and mention that in the description before the code.

$ python -m pip install virtualenv

### PR DESCRIPTION
**Pull request by amr-atif**
the documentation is not clear on this point as we need to add a command to install virtualenv package to be able to create a virtual environment

$ python -m pip install virtualenv

and added a description before it.
closes #133

### CODE REVIEW

**Comment by wlav** [comment]
I think that at this point (with most Pythons in the wild newer than 3.3), it's better to change the text wholesale to use `venv` with a reference to `virtualenv` just for old Pythons, rather than the opposite as is the case now.

**Comment by amr-atif** [comment]
I have edited the creation of venv commands so we can use venv instead of virtualenv as most people use modern versions of python.
then I updated the description and added a note to explain how to use virtualenv for old versions of python.

**Comment by amr-atif** [comment]
What do you think about it this way, do you recommend a better way that will make it more clear? @wlav

**Comment by wlav** [comment]
Thanks!

**Pull request merged**
